### PR TITLE
multi -seq

### PR DESCRIPTION
**Pull request by AmaniA**

### CODE REVIEW

**Comment by AmaniA** [comment]
```
multi-Seq
```

**Comment by AmaniA** [comment]
Hi Francis,

I want to ask what is the way you were thinking to approach and deal with the multi sequences. Because now I'm thinking of using multi-threads. But, I wanted to know if you have another idea. Thanks.

Best,
Amani
Sent from Outlook Mobilehttps://aka.ms/qtex0l

**Comment by fcocjin** [comment]
The way you had it BLASTing from command line seems to have worked. I am going to test it someday soon to see if I can divide up the results by the input that produced them. For example, if we BLAST sequences A, B, and C, I want to make sure we know what BLAST result came from BLASTing A, BLASTing B, and BLASTing C.

**Comment by AmaniA** [comment]
Thank you.

**Pull request merged**
